apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-disk
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

# forma de usar em nuvem é passando o sc e o provisioner