apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-noticias-statefulset
spec:
  serviceName: svc-db-noticias
  replicas: 1
  selector:
    matchLabels:
      app: db-noticias-statefulset
  template:
    metadata:
      name: db-noticias-statefulset
      labels:
        app: db-noticias-statefulset
    spec:
      containers:
      - name: db-noticias-container
        image: aluracursos/mysql-db:1
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-configmap
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/mysql
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
      volumes:
        - name: db-disk
          persistentVolumeClaim:
            claimName: db-noticias-pvc
