apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias-container
        image: aluracursos/portal-noticias:1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: portal-noticias-configmap
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe: 
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          initialDelaySeconds: 3
          failureThreshold: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: 10m
          limits:
            memory: "128Mi"
            cpu: 500m
  replicas: 3
  selector: 
    matchLabels:
      app: portal-noticias