apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sistema-noticias-sessao-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard

