apiVersion: v1
kind: PersistentVolume
metadata:
  name: sistema-noticias-files-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/d/Projetos/Kubernetes/Alura/dados/uploads
    type: DirectoryOrCreate