apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sistema-noticias-files-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
