apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  serviceName: svc-sistema-noticias
  replicas: 3
  selector:
    matchLabels:
      app: sistema-noticias
  template:
    metadata:
      name: sistema-noticias-statefulset
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: sistema-noticias-container
        image: aluracursos/sistema-noticias:1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: sistema-noticias-configmap
        volumeMounts:
          - name: sessao
            mountPath: /tmp
          - name: uploads
            mountPath: /var/www/html/uploads
        livenessProbe:
          httpGet: 
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe: 
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          initialDelaySeconds: 3
          failureThreshold: 10
      volumes:
        - name: sessao
          persistentVolumeClaim:
            claimName: sistema-noticias-sessao-pvc
        - name: uploads
          persistentVolumeClaim:
            claimName: sistema-noticias-files-pvc
