apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-loadbalancer
spec:
  type: LoadBalancer
  ports: 
    - port: 30003
      nodePort: 30002
      targetPort: 80
  selector:
    app: primeiro-pod